version: "3.8"
services:
  download-pdf:
    build: ./
    image: benlirio/download-pdf
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./src/public/
        target: /run/app/download-pdf/src/public/
